package Exception;

public class Test 
{
	public static void main(String[] args) {
		try
		{
			int a=10/2;
			System.out.println(a);
			
			
	//	String s=null;
	//	System.out.println(s.length());
		
	//	String s="a";
	//	int a=Integer.parseInt(s);
	//	System.out.println(a);
		
	/*	int a[]=new int[2];
		a[0]=10;
		a[1]=20;
		a[2]=30;
		
		System.out.println(a[0]);
		System.out.println(a[1]);
		System.out.println(a[2]); */
		}
		catch (Exception e) {
		System.out.println(e);
		}
	
	}
}
